// Mocks generated by Mockito 5.4.4 from annotations
// in user_management/test/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:user_management/data/datasources/hive_user_data_source.dart'
    as _i3;
import 'package:user_management/data/models/user_model.dart' as _i4;
import 'package:user_management/domain/entities/user.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HiveUserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveUserDataSource extends _i1.Mock
    implements _i3.HiveUserDataSource {
  MockHiveUserDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i4.UserModel> get hiveBox => (super.noSuchMethod(
        Invocation.getter(#hiveBox),
        returnValue: _FakeBox_0<_i4.UserModel>(
          this,
          Invocation.getter(#hiveBox),
        ),
      ) as _i2.Box<_i4.UserModel>);

  @override
  _i5.Future<List<_i6.User>> fetchUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchUsers,
          [],
        ),
        returnValue: _i5.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i5.Future<List<_i6.User>>);

  @override
  _i5.Future<void> saveUser(_i6.User? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
